name: ${project.name}
main: com.vexsoftware.votifier.VotifierPlus
version: ${project.version}
description: A plugin that gets notified when votes are made for the server on toplists.
author: Ben12345rocks
api-version: 1.13